= Use case 1 - Simple Despatch

This use case is a simple Despatch where no handling units are used in the Despatch Advice.
There are only two parties (legal entities) in this use case.

****

Description::
This use case is a simple despatch where no handling units are used in the Despatch Advice.
There are only two parties (legal entities) in this use case.

Parties involved::
Despatch party (In UBL: DespatchSupplierParty) (same legal entity as the Supplier/Seller in this use case) +
Consignee party (In UBL: DeliveryCustomerParty) (same legal entity as the Customer/Buyer in this use case)

Assumptions::
.  The Seller has received one order from the Buyer with
..  2 lines (2 articles)
..   to be delivered at one delivery address
..  at the same time.
.  The Seller has accepted the order without changes.
.  The Despatch party delivers the complete order as accepted

Flow::
.  The Seller collects the ordered articles
.  The Seller loads the articles in boxes
.  The Despatch party creates a Despatch advice message
.  The Despatch party sends Despatch advice message to the Consignee
.  The Consignee party receives the Despatch advice message
.  The Consignee party uses the content in the Despatch advice message for registration receipt.
..  Two despatch lines, two items (No handling units in the message)

Result::
.  The Despatch advice message helped the Consignee party to prepare receipt
..  At the right time
..  At the right place (address)
.  The Despatch advice message helped the Consignee party in the process of register receipt to identify the
..  Order
..  The order lines
..  The articles
..  The delivered quantity

****