site_draft:
  id: ehf-postaward-g3-draft
  type: site
  path: target/site
  properties:
    domain: anskaffelser.dev
    path: postaward/g3/spec/draft

site_current:
  mode: release
  id: ehf-postaward-g3-current
  type: site
  path: target/site
  properties:
    domain: anskaffelser.dev
    path: postaward/g3/spec/current