= Use case 3 – Catalogues replace from the provider and accept from the receiver

This is a *Replace* of the catalogue based on Use case 1 and 2.

****

Description::
The provider sends a catalogue replace to the receiver.
The catalogue contains all the contracted items and replaces the previous accepted catalogue.
After receiving the catalogue, the buyer accepts the catalogue using a response message.

Parties involved::
Catalogue Provider (same legal entity as the Supplier/Seller in this use case) +
Catalogue Receiver (same legal entity as the Customer/Buyer in this use case)

Assumptions::
.  The Seller has previously sent a new catalogue to the Buyer which has been accepted.
.  The Seller has sent an update of the catalogue which was rejected by the buyer
.  The Seller sends a replace catalogue
..  All articles that the supplier had identified in the contract, including the new one in the rejected catalogue.
..  One article from the previous accepted catalogue is not in this catalogue.
..  Three more new articles are added.
Shampoo presented in a hierarchy.

Flow::
.  The Seller identifies the items to be in the Catalogue update
.  The Provider creates a Catalogue message
.  The Provider sends the message to the Receiver
.  The Buyer verifies the content in the message and accepts the catalogue.
.  The Buyer sends a Catalogue response with accept.

Result::
.  The Buyer has all the articles and the contracted prices in the ERP-system and may start ordering
.  The ordering process is easy when you have all necessary information in the ERP-system.

****