== EHF Fakturering (Peppol BIS billing) as a carrier of CO2 values

EHF invoice can also be used to express CO2 values (A1-A3) for each individual product. EHF invoice (Peppol BIS billing 3.0) has two free fields (Additional Item Properties): a name field and a value field. These fields can be used by the supplier to express the CO2 value for the product:

Definitions coordinated with Denmark (ERST) and Byggstand in Norway

include::../{shared-dir}/content/co2-emissions-def.adoc[]

NB!:: Base Quantity does not impact the Emission Factor and the Emission Factor Quantity (which are defined per invoiced unit, not per price unit).

[source,xml]
.UBL XML eksempel EHF faktura

----
<?xml version="1.0" encoding="UTF-8"?>
<Invoice
xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
<cbc:ID/>
<cbc:IssueDate/>
<cac:AccountingSupplierParty/>
<cac:AccountingCustomerParty/>
 <cac:LegalMonetaryTotal>
<cbc:PayableAmount/>
</cac:LegalMonetaryTotal>
 <cac:InvoiceLine>
    <cbc:ID/>
    <cbc:LineExtensionAmount/>
        <cac:Item>
             <cac:AdditionalItemProperty>
                  <cbc:Name>EmissionFactor</cbc:Name>
                  <cbc:Value>0.20</cbc:Value>
              </cac:AdditionalItemProperty>
              <cac:AdditionalItemProperty>
                  <cbc:Name>NetEmissionQuantity</cbc:Name>
                 <cbc:Value>1.4</cbc:Value> </cac:AdditionalItemProperty>
            <cac:AdditionalItemProperty>
                <cbc:Name>EmissionFactorSource</cbc:Name>
                <cbc:Value>Database</cbc:Value> </cac:AdditionalItemProperty>
           <cac:AdditionalItemProperty>
                <cbc:Name>EmissionFactorCalculationRate</cbc:Name>
                <cbc:Value>0.25</cbc:Value> </cac:AdditionalItemProperty>
          <cac:AdditionalItemProperty>
               <cbc:Name>EmissionFactorCalculationUnit</cbc:Name>
              <cbc:Value>KGM</cbc:Value>
         </cac:AdditionalItemProperty>
</cac:Item>
</cac:InvoiceLine>
</Invoice>
----

Innhente miljøinformasjon for enkeltprodukter via ekstern database::

For obtaining environmental information stored in external databases, in the form of machine-readable EPDs or Digital Product Passports, the free fields can also be used. The purpose is that the digital files sent do not become too large. The information collected by the client/buyer can be used in the analysis of the company's behaviour and used for various reporting purposes. The environmental properties of the product in combination with information from the ordering process (EHF order and order confirmation) and the delivery process (EHF despatch advice), can form a more complete data basis of the environmental footprint from production until the product is with the client/buyer.
[source,xml]
.Below you will find an xml example:
----
<cac:InvoiceLine>
           <cbc:ID/>
          <cbc:LineExtensionAmount/>
                     <cac:Item>
                                <cac:AdditionalItemProperty>
                                     <cbc:Name>CO2EmissionFactorSource</cbc:Name>
                                     <cbc:Value>[lenke til miljødatabase]</cbc:Value>
                                </cac:AdditionalItemProperty>
----