= Value Added Tax (Norwegian MVA)

Norwegian tax categories are mapped according to this table for use with PEPPOL BIS Billing 3.0:

include::../{shared-dir}/content/mva.adoc[]

IMPORTANT: Rounding of amount related to VAT must follow the link:https://www.skatteetaten.no/rettskilder/type/uttalelser/prinsipputtalelser/prinsipputtalelse-vedrorende-oreavrunding-av-vederlag-i-salgsdokumentet[statement of principal] (link:https://www.skatteetaten.no/en/rettskilder/type/uttalelser/prinsipputtalelser/statement-of-principle-regarding-rounding-off-remuneration-in-the-sales-document[english translation]).

IMPORTANT: Rates used in the invoice/credit note must follow the official rates defined by link:https://www.skatteetaten.no/[The Norwegian Tax Administration].
Implementers in need of exempt is required to request such an exempt using link:https://www.altinn.no/skjemaoversikt/skatteetaten/kontaktskjema---skatteetaten-naringsdrivende-/[RF-1306] before invoicing.
In the case of exempt is the rate (not amount) to be changed accordingly due to rules in EN16931.
Documentation of exempt must be shared with Difi upon request.

Explanation of some VAT-codes:

* E (VAT exempt): According to link:https://lovdata.no/dokument/NL/lov/2009-06-19-58[Lov om merverdiavgift] shall E be
used for products and services that is stated in ยง3-2 to ยง3-20.

* Z (VAT exempt- Goods and services not included in the VAT regulations): According to link:https://lovdata.no/dokument/NL/lov/2009-06-19-58[Lov om merverdiavgift]
shall Z be used for products and services that is stated in chapter 6.

* link:https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL5305/[Peppol BIS Billing 3.0 VAT code list] operates with a code O (Services outside scope of tax).
This code shall be used for products and services for businesses that are except from link:https://lovdata.no/dokument/NL/lov/2009-06-19-58[Lov om merverdiavgift].


Please see the link:http://docs.peppol.eu/poacc/billing/3.0/bis/#_value_added_tax_vat[PEPPOL BIS Billing 3.0 documentation]
for more information about value added tax.