[appendix]
= Standard Business Document Header (SBDH)

Standard Business Document Header (SBDH) provides an envelope which contains key data when exchanging business documents between different systems.
SBDH enables integration or transmission of document between:

* internal application,
* enterprise applications, and
* business-to-business infrastructure.

The envelope information will determine the routing (Senders and Receivers EndpointID) and processing of a document
based on header information. For example, routing business document (transforming information) from an external originator to receiver.

NOTE: SBDH is *RECOMMENDED* to be used in combination with EHF Payment Request.

The use of SBDH follows the link:https://peppol.eu/downloads/the-peppol-edelivery-network-specifications/[specification provided by OpenPEPPOL].

EHF Payment Request 3.0 is different from most transmissions in the PEPPOL Network as both sender party's identifier and receiver party's identifier MUST have identifier.

The following example describes the SBDH implementation, and notice how the key data is implemented.

.Example of how to implement SBDH.
[source, xml, indent=0]
----
<?xml version="1.0" encoding="UTF-8"?>
<StandardBusinessDocument xmlns = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader">
  <StandardBusinessDocumentHeader>
    <HeaderVersion>1.0</HeaderVersion>
    <Sender>
      <Identifier Authority="iso6523-actorid-upis">0192:123456785</Identifier> <!--1-->
    </Sender>
    <Receiver>
      <Identifier Authority="iso6523-actorid-upis">0192:123456785</Identifier> <!--2-->
    </Receiver>
    <DocumentIdentification>
      <Standard>urn:oasis:names:specification:ubl:schema:xsd:Invoice-2</Standard>
      <TypeVersion>2.2</TypeVersion>
      <InstanceIdentifier>51ddd910-9a95-4b0f-ab01-b3cc0db59d01</InstanceIdentifier> <!--3-->
      <Type>Invoice</Type>
      <CreationDateAndTime>2019-08-14T13:30:00Z</CreationDateAndTime> <!--4-->
    </DocumentIdentification>
    <BusinessScope>
      <Scope>
        <Type>DOCUMENTID</Type>
        <InstanceIdentifier>urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:fdc:difi.no:2017:ehf:spec:payment-request:3.0::2.2</InstanceIdentifier> <!--5-->
      </Scope>
      <Scope>
        <Type>PROCESSID</Type>
        <InstanceIdentifier>urn:fdc:difi.no:2019:ehf:postaward:g3:07:1.0</InstanceIdentifier> <!--6-->
      </Scope>
    </BusinessScope>
  </StandardBusinessDocumentHeader>
  <Invoice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
           xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
           xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"> <!--7-->

      <!-- Rest of the Payment Request input -->

  </Invoice>
</StandardBusinessDocument>
----
<1> Identification of the sender, where the value MYST be the organization number of the handling organization (`0192:[organization number]`).
<2> Identification of the receiver, where the value MYST be the organization number of the handling organization (`0192:[organization number]`).
<3> Universal Unique Identifier (UUID), recommend version 4 UUID.
<4> Date and time for when this envelope was created. Use format: `YYYY-MM-DDThh:mm:ssZ`, where T indicate a divider and Z indicates UTC.
<5> Document type identifier for EHF Payment Request 3.0.
<6> Process identifier for EHF Payment Request 3.0.
<7> EHF Payment Request 3.0 instance document.
