= Standard Business Document Header (SBDH)


Standard Business Document Header (SBDH) provides a document header which contains key data (information) about a specific business document.
SBDH enables integration or transmission of document between:

* internal application,
* enterprise applications, and
* business-to-business infrastructure.

The standard header information will determine the routing (Senders and Receivers EndpointID) and processing of a document
based on header information. For example, routing business document (transforming information) from an external originator to receiver.

In general, SBDH is viewed as an "envelope" in electronic message processes. For example, when we send files to other PEPPOL Access Points
we need to wrap the payload (invoice, order, etc.) in an envelope (SBDH). We also use the same envelope when receiving files from PEPPOL.

NOTE: A header is not mandatory in EHF Payment Request, but we *recommend* to use a header.

A header is placed at the beginning of the data structure and includes information (key data) about:

* Header version
* Senders identifier: format "0192:NNNNNNNNN", where N is organisation number
* Buyers identifier: format "0192:NNNNNNNNN", where N is organisation number
* Invoice namespace and version
* UUID
* Creation date and time
* Document identifier = <Invoice Namespace>##<CustomizationID>::<UBL Invoice version number>
* Process identifier = ProfileID

NOTE: Sender party's identifier and Receiver party's identifier MUST have same number, i.e. organisation number.

Read more about SBDH here: link:https://peppol.eu/downloads/the-peppol-edelivery-network-specifications/[PEPPOL'S Website] or
link:https://www.gs1.org/standards/edi-xml-gdsn-gs1-uncefact-xml-profiles/sbdh-technical-specifications/1-3[Technical specification from GS1].

The following example describes the SBDH implementation, and notice how the key data is implemented.

.Example of how to implement SBDH.
[source, xml, indent=0]
----
include::../../../../rules/payment-request-3.0/snippets/sbdh-example.xml[tags=SBDH]
----
<1> Standard business document header namespace.
<2> Standard business document header element that contains information about the business document.
<3> Sender of the message *must* use attribute "Authority= iso6523-actorid-upis" together with a value "0192:NNNNNNNNN",
where _N = Organisation number_. *Note that*: Senders organisation number MUST be the same as Receivers organisation number.
<4> Receiver of the message *must* use attribute "Authority= iso6523-actorid-upis" together with a value "0192:NNNNNNNNN",
    where _N = Organisation number_. *Note that*: Receivers organisation number MUST be the same as Senders organisation number.
<5> Invoice Namespace from OASIS 2.2
<6> Universal Unique Identifier (UUID), recommend version 4 UUID.
<7> Date and time for when this envelope was created. Use format: "2019-05-20T09:00:00Z", where Z indicates UTC.
<8> Determine the scope of the business message (envelope). Element "BusinessScope" MUST contain two scope elements: Document identifier (DOCUMENTID) and Process identifier (PROCESSID).
<9> The first scope element "DOCUMENTID", document identifier, selected from codelist "Business Identifiers".
<10> DocumentID's instance identifier, from codelist "Instance Identifier".
<11> Second scope element "PROCESSID", process identifier, selected from codelist "Business Identifiers".
<12> ProcessID's instance identifier, from codelist "Instance Identifier".