== Use case 2 - Research project funds

****

Description::
This use case illustrates the use of Payment Request, where a research project from University of Tromso apply
for funding.

Parties involved::
Applicant +
Payment Party +
Party on behalf of applicant +
Review Party

Assumptions::
. An applicant apply for research project funding.
. This research project is related to University of Tromso (Party on behalf of applicant).
. The Norwegian Ministry of Education and Research (Review Party) provide 10000kr in funding for research projects that
fulfil the criterias.


Flow::
. An applicant apply for research funds through the party on behalf of applicant (University of Tromso).
. The University (Party on behalf of applicant) sends an application to The Norwegian Ministry of Education and Research (Review Party).
. The Review party evaluate the application and compare against a list of criteria.
. The Review party approve the application and send an EHF Payment Requst to their accounting system (Payment Party).
. The Payment party receives the electronic message from the Review party and prepare a payment to the applicant.
. Finally, the payment party sends payment to the applicant.


Result::
. The Applicant receives funds from the Norwegian Ministraty of Education and Research's accounting system (Payment Party).
. The Applicant receives the financial support in few days by using electronic processes.



****
